schema: ./*.graphql
extensions:
  codegen:
    generates:
      audio-api/src/generated-types.ts:
        plugins:
          - typescript
          - typescript-resolvers
  diff:
    baseSchema: your-base-schema-here
